rootページにアクセスすると、hello worldを表示するように変更
ogontaro/hajimeteno_rails pull request #2
Opened 2017-04-08 06:26 UTC by masuno

### 概要
rootページにアクセスすると、hello worldを表示するように変更

### 対応内容
- [ ] 実装
- [ ] 動作確認

### レビュー項目
- [ ] 動作確認
- [ ] コードレビュー

2017-04-08 06:30 UTC, ogontaro requested changes
文中にコメントしましたので、確認お願いします。

2017-04-08 06:30 UTC, ogontaro commented on app/controllers/application_controller.rb
> +    render html: "こんにちは世界😀!"
@masuno 本当は絵文字は環境によって動作しない場合があるので削除してほしいです。

2017-04-08 06:30 UTC, ogontaro commented on config/routes.rb
> +  root 'application#hello'
いいかんじです。

2017-04-08 06:32 UTC, ryosuketter commented
![寿司ゆき:thanks](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/04.png)

2017-04-08 06:34 UTC, ryosuketter requested changes

2017-04-08 06:34 UTC, ryosuketter commented on app/controllers/application_controller.rb
> +    render html: "こんにちは世界😀!"
![寿司ゆき:sorry](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/05.png)

2017-04-08 06:34 UTC, ryosuketter commented on config/routes.rb
> +  root 'application#hello'
![JS Girls:no](https://tomo-e.github.io/js-girls/images/10.png)

2017-04-08 06:39 UTC, masuno commented
@ogontaro 指摘事項を修正しましたので、再度ご確認をよろしくお願いいたします🙏

2017-04-08 06:40 UTC, ryosuketter commented
![JS Girls:notice](https://tomo-e.github.io/js-girls/images/38.png)

2017-04-08 06:41 UTC, ogontaro approved these changes
LGTMです。

2017-04-08 06:42 UTC, ryosuketter approved these changes

2017-04-08 06:43 UTC, ryosuketter commented
マージだ！！
![寿司ゆき:sigh](https://d1zd1v0cxnbx2w.cloudfront.net/images/sets/sushiyuki/06.png)

2017-04-08 06:43 UTC, merged

2017-08-05 03:39 UTC, ryosuketter commented
なつかしい